cask_args appdir: '/Applications'

brew 'bash-completion'
brew 'bower'
brew 'chruby'
brew 'git'
brew 'grunt'
brew 'heroku/brew/heroku'
brew 'htop'
brew 'hub'
brew 'imagemagick'
brew 'jsonpp'
brew 'mongodb'
brew 'neovim'
brew 'redis'
brew 'ruby-install'
brew 'the_silver_searcher'
brew 'tmux'
brew 'yarn'
brew 'awscli'
brew 'pv'
brew 'blackbox'
brew 'gnupg'

cask 'TextMate'
cask 'iterm2'
cask 'java'
cask 'vagrant'
cask 'virtualbox'
cask 'gpg-suite'

tap 'cloudfoundry/tap'
brew 'cloudfoundry/tap/cf-cli'
