#!/bin/sh
brew bundle

# Symlink dot files
configs=(gemrc gitconfig gitignore profile rspec vimrc tmux.conf)

for file in ${configs[*]}; do
  # Delete file if it is a symlnik
  if [ -h ~/.$file ]; then
    rm ~/.$file
  fi
  # Symlink if there's no file
  if [ ! -f ~/.$file ]; then
    ln -s $(pwd)/$file ~/.$file
  fi
done

if [ -f ~/.$file ]; then
  rm ~/.config/nvim/init.vim
fi
mkdir -p ~/.config/nvim
ln -s $(pwd)/init.vim ~/.config/nvim/init.vim

# Enable text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true
defaults write com.apple.screencapture location ~/Downloads
killall Finder
