#!/bin/sh

git submodule init
git submodule update

# Symlink dot files
ln -s $(pwd)/gemrc      ~/.gemrc
ln -s $(pwd)/gitconfig  ~/.gitconfig
ln -s $(pwd)/gitignore  ~/.gitignore
ln -s $(pwd)/profile    ~/.profile
ln -s $(pwd)/rspec      ~/.rspec
ln -s $(pwd)/vimrc      ~/.vimrc
ln -s $(pwd)/vim        ~/.vim
ln -s $(pwd)/tmux.conf  ~/.tmux.conf

# Symlink vi to vim
ln -s /usr/local/bin/vim /usr/local/bin/vi

# Enable text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true && killall Finder

# Compile the Command-T extension
chruby system
cd vim/bundle/Command-T/ruby/command-t
ruby extconf.rb
make clean
make

# TODO not sure how to get back to repo root

brew install bash-completion
